### ISSUE TITLE
TODO

### ISSUE THREAD

**Issue by leifdenby** [leifdenby/CloudModels.jl#9]
- [ ] Bayesian parameter estimation for prescribed environment and IC
- [ ] RICO simulation profile interpolation
- [ ] RICO simulation IC loading
- [ ] RICO simulation BC loading
- [ ] Switch from ComponentArrays to LabelledArrays (https://github.com/SciML/LabelledArrays.jl) https://github.com/leifdenby/CloudModels.jl/pull/10
- [ ] Work out how to do integration with UnitFull IC with OrdinaryDiffEq
- [ ] Create Plot recipe for plotting ambient and solution profiles
